import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { getOdooSessionId } from '@/lib/odoo/odoo-helper';

// Use GEMINI_API_KEY or fallback to GOOGLE_GEMINI_API_KEY
const API_KEY = process.env.GEMINI_API_KEY || process.env.GOOGLE_GEMINI_API_KEY || '';
const genAI = new GoogleGenerativeAI(API_KEY);

export const dynamic = 'force-dynamic';
export const maxDuration = 60; // Gemini image generation can take up to 60 seconds
export const runtime = 'nodejs'; // Ensure nodejs runtime for better compatibility

export async function POST(request: NextRequest) {
  try {
    // Check API key first
    if (!API_KEY) {
      console.error('❌ GEMINI_API_KEY not configured!');
      return NextResponse.json(
        { success: false, error: 'Gemini API key not configured' },
        { status: 500 }
      );
    }

    const sessionId = await getOdooSessionId();
    if (!sessionId) {
      return NextResponse.json(
        { success: false, error: 'Sessione non valida. Effettua il login.' },
        { status: 401 }
      );
    }

    const { productName, productDescription, productId, productModel, photoUrls } = await request.json();

    if (!productName) {
      return NextResponse.json(
        { success: false, error: 'Nome prodotto mancante' },
        { status: 400 }
      );
    }

    console.log('🎨 Generating product image with Gemini for:', productName);
    console.log('📸 Reference photos:', photoUrls?.length || 0);

    const model = genAI.getGenerativeModel({ model: 'gemini-3.1-flash-image-preview' });

    // Download reference photos if provided
    const photoParts: any[] = [];
    if (photoUrls && photoUrls.length > 0) {
      for (const url of photoUrls.slice(0, 4)) {
        try {
          const photoRes = await fetch(url);
          const arrayBuf = await photoRes.arrayBuffer();
          const base64 = Buffer.from(arrayBuf).toString('base64');
          const mime = photoRes.headers.get('content-type') || 'image/jpeg';
          photoParts.push({ inlineData: { data: base64, mimeType: mime } });
        } catch (e) {
          console.warn('⚠️ Failed to download photo:', url);
        }
      }
      console.log(`📸 Downloaded ${photoParts.length} reference photos`);
    }

    const imagePrompt = photoParts.length > 0
      ? `Guarda attentamente queste foto reali del prodotto "${productName}". ${productDescription || ''}

Genera una NUOVA foto professionale per e-commerce basandoti sulle foto reali:

REGOLE FONDAMENTALI:
- Il prodotto deve essere IDENTICO a quello nelle foto: stessa forma, stesse dimensioni, stessa etichetta, stessi colori
- NON inventare o modificare l'etichetta, il design, il logo, i colori della confezione
- Se nelle foto c'è un cartone/confezione multipla, mettilo DIETRO. Davanti metti 1-2 unita singole
- Se il prodotto e' una lattina, deve restare una lattina. Se e' una busta, deve restare una busta. Se sono bottiglie, devono restare bottiglie
- Migliora SOLO: illuminazione, nitidezza, sfondo (bianco pulito), composizione
- Il risultato deve sembrare una foto da studio professionale dello STESSO identico prodotto
- Formato QUADRATO (1:1), prodotto al centro, riempie 70-80% del frame
- Il cliente che compra online deve riconoscere ESATTAMENTE il prodotto che ricevera`
      : `Professional product photography of ${productName}. ${productDescription || ''}. IMPORTANT: Generate a SQUARE image (1:1 aspect ratio). Clean white background, e-commerce style, well-lit, centered composition, product fills 70-80% of the frame, studio lighting, sharp focus.`;

    console.log('⏳ Calling Gemini API...');
    const startTime = Date.now();

    const contentParts: any[] = [...photoParts, { text: imagePrompt }];
    const result = await model.generateContent(contentParts);

    const elapsedTime = ((Date.now() - startTime) / 1000).toFixed(2);
    console.log(`✅ Gemini API responded in ${elapsedTime}s`);

    const response = result.response;

    // Check if image was generated
    if (!response || !response.candidates || response.candidates.length === 0) {
      console.error('❌ No image generated by Gemini');
      console.error('Response:', JSON.stringify(response, null, 2));
      return NextResponse.json({
        success: false,
        error: 'Nessuna immagine generata da Gemini'
      }, { status: 500 });
    }

    console.log(`📊 Response has ${response.candidates.length} candidate(s)`);

    // Extract image data from response
    // Gemini 2.5 Flash Image returns images inline in the response
    const candidate = response.candidates[0];
    const parts = candidate.content?.parts || [];

    let imageBase64 = null;
    let imageMimeType = null;

    // Find the image part in the response
    for (const part of parts) {
      if (part.inlineData && part.inlineData.data) {
        imageBase64 = part.inlineData.data;
        imageMimeType = part.inlineData.mimeType;
        break;
      }
    }

    if (!imageBase64) {
      console.error('❌ No image data found in Gemini response');
      console.error('Parts structure:', JSON.stringify(parts.map(p => Object.keys(p)), null, 2));
      return NextResponse.json({
        success: false,
        error: 'Dati immagine non trovati nella risposta di Gemini'
      }, { status: 500 });
    }

    console.log('✅ Image generated successfully with Gemini 2.5 Flash Image');
    console.log('📊 Image format:', imageMimeType);
    console.log('📊 Image size:', Math.round(imageBase64.length * 0.75 / 1024), 'KB');

    // If productId is provided, upload to Odoo
    if (productId) {
      try {
        console.log(`📤 Uploading image to Odoo product ${productId}`);

        const odooUrl = process.env.ODOO_URL;

        // Update product with image
        const updateResponse = await fetch(`${odooUrl}/web/dataset/call_kw`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Cookie': `session_id=${sessionId}`
          },
          body: JSON.stringify({
            jsonrpc: '2.0',
            method: 'call',
            params: {
              model: productModel || 'product.template',
              method: 'write',
              args: [
                [productId],
                { image_1920: imageBase64 }
              ],
              kwargs: {},
            },
            id: Math.floor(Math.random() * 1000000000)
          })
        });

        const updateData = await updateResponse.json();

        if (updateData.error) {
          console.error('⚠️ Error updating product image in Odoo:', updateData.error);
        } else {
          console.log('✅ Product image uploaded to Odoo successfully');
        }
      } catch (odooError) {
        console.error('⚠️ Failed to upload image to Odoo:', odooError);
      }
    }

    return NextResponse.json({
      success: true,
      message: 'Immagine generata con successo con Gemini 2.5 Flash Image',
      imageBase64: imageBase64,
      mimeType: imageMimeType,
      uploaded: !!productId
    });

  } catch (error: any) {
    console.error('❌ Error generating image with Gemini:', error);
    return NextResponse.json(
      {
        success: false,
        error: error.message || 'Errore durante la generazione dell\'immagine'
      },
      { status: 500 }
    );
  }
}
